server:
  port: 8080
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: "debug"
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb"
---
spring:
  config:
    activate:
      on-profile: "dev"
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: "sec"
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: "test"
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: "prod"
server:
  port: 9000